import type { Metadata } from "next";
import { Oxanium } from "next/font/google";

import Header from "@/components/header";
import "./globals.css";

const oxanium = Oxanium({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-br">
      <body className={oxanium.className}>
        <Header />

        {children}
      </body>
    </html>
  );
}
